dataset:
  class_path: dataset.ImageNetDataset
  init_args:
    data_dir: '/usr/local/data'
    batch_size: 128
    augment: True
model:
  class_path: model.ConvNet
  init_args:
    num_class: 10
    kernel_size: 3
    num_layers: 5
